# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ab7e88bd0fb9fe7c668a3369a97d0341fb581867d315ad68d140bc63a077638a3a2b08c3cba063435d4b748ec77a7a415fb6b462aec6826b5a61f630607205e

test:
  secret_key_base: cd10cd8160980e080f32d45a1fa652ce6004dc8f10911bc3e316d8ec6cbbb97fad75517274d4d45f1423532a0cb6f283887c19d94eb45afaa547d2f145dd03df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
